// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfdpXvcRCu0gntRtUmnyMnUPOigDmXj74',
    appId: '1:75782560054:web:4daa3332cca9ffafca3b97',
    messagingSenderId: '75782560054',
    projectId: 'convocraft-97e30',
    authDomain: 'convocraft-97e30.firebaseapp.com',
    storageBucket: 'convocraft-97e30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvD2Qr6yBWFhZSGujVNj9lsowiacknzjE',
    appId: '1:75782560054:android:a57bf10d793de5a4ca3b97',
    messagingSenderId: '75782560054',
    projectId: 'convocraft-97e30',
    storageBucket: 'convocraft-97e30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB8c9ke2E-c3Bjb_6jqZjSKTqMK5nekPk',
    appId: '1:75782560054:ios:b434eae55ff41275ca3b97',
    messagingSenderId: '75782560054',
    projectId: 'convocraft-97e30',
    storageBucket: 'convocraft-97e30.appspot.com',
    iosBundleId: 'com.example.convocraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB8c9ke2E-c3Bjb_6jqZjSKTqMK5nekPk',
    appId: '1:75782560054:ios:46e3f04f25cd1d8eca3b97',
    messagingSenderId: '75782560054',
    projectId: 'convocraft-97e30',
    storageBucket: 'convocraft-97e30.appspot.com',
    iosBundleId: 'com.example.convocraft.RunnerTests',
  );
}
